name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4

      - 
        name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JRLMGITOPSACR_LOGIN_SERVER }}
          username: ${{ secrets.JRLMGITOPSACR_USERNAME }}
          password: ${{ secrets.JRLMGITOPSACR_PASSWORD }}

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - 
        name: Push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          tags: |
            ${{ vars.JRLMGITOPSACR_LOGIN_SERVER }}/frontend:${{ github.sha }}